Agrego lectura con separador para solventar parser error
eloychang/andreani_aa_tools pull request #6
Opened 2022-11-18 15:11 UTC by daiana-alonso

Por default intenta interpretarlo como archivo separado por comas, si no puede parsearlo lo hace por ';'.

2023-01-06 12:45 UTC, eloychang requested changes

2023-01-06 12:45 UTC, eloychang commented on src/aa_tools/datalake.py
> +                return pd.read_csv(BytesIO(downloaded_bytes), sep=',')
Mejor colocar el separador, y los decimales como un parámetro del método

2023-01-06 13:50 UTC, daiana-alonso commented on src/aa_tools/datalake.py
> +                return pd.read_csv(BytesIO(downloaded_bytes), sep=',')
Separador agregado como parámetro... decimales?

2023-01-06 13:53 UTC, eloychang commented on src/aa_tools/datalake.py
> +                return pd.read_csv(BytesIO(downloaded_bytes), sep=',')
si, en caso de que también vengan los decimales como ',' en lugar de '.'

2023-01-09 12:03 UTC, eloychang approved these changes

2023-01-09 12:55 UTC, merged